#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# validate commit
npx --no-install commitlint -g commitlint.config.js --edit "$1"

LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feature|bugfix|improvement|hotfix)\/[a-z0-9-]+$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

# validate branch name
# shellcheck disable=SC2039
if [ ! $local_branch =~ $valid_branch_regex ] && [ ! "$local_branch" == "staging" ] && [ ! "$local_branch" == "prod" ]; then
  echo "$message"
  exit 1
fi
