name: Check PR

on:
  pull_request:
    branches: [ prod, 'example/**' ]
    types: [ opened, synchronize, reopened ]

env:
  NODE_VERSION: 22.23.2
  ENABLE_CACHE: yes

jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-check-pr
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: ${{ env.ENABLE_CACHE == 'yes' && 'npm' || '' }}

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Commit lint PR title
        run: echo "${{ github.event.pull_request.title }}" | npx --no-install commitlint -g commitlint.config.js

      - name: Check eslint
        run: npm run lint:check

      - name: Typescript check
        run: npm run ts:check

      - name: Stylelint check
        run: npm run style:check

      - name: Build check
        run: npm run build -- --throw-warnings

      - name: Client size budget
        run: npm run size:check

      - name: Smoke check
        run: npm run smoke
