name: Semantic release

on:
  push:
    branches: [ prod ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      app-build-args: --unlock-robots

  release:
    needs: [build]
    uses: ./.github/workflows/release-r.yml
    with:
      has-release-asset: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  docker-build:
    needs: [build, release]
    uses: ./.github/workflows/docker-build.yml
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}/web
      version: ${{ needs.release.outputs.version }}
      app-build-path: ./build
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-aws:
    needs: [docker-build]
    uses: ./.github/workflows/deploy-aws.yml
    with:
      image: ${{ needs.docker-build.outputs.image-tag }}
      service: vite-template
      cluster: Development
      task-container-name: web
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
